### ISSUE TITLE
waitForTimeout from config file doesnt work in wait* methods by default

### ISSUE THREAD

**Issue by Elverslane** [codecept-js/CodeceptJS#2150]
#### What are you trying to achieve?
i want to use any of wait* methods w/o hardcoding timeout because it already declared in config file.
#### What do you get instead?
instead i get TS error 
![Screenshot 2020-01-16 at 14 32 17](https://user-images.githubusercontent.com/17493900/72669744-ae9f0400-3a46-11ea-8ad0-23e855cf4a0e.png)

### Details

* CodeceptJS version: 2.3.6
* Operating System: macos
* puppeteer 

Here's the relevant part from our config:
```
   { 
     helpers: {
        Puppeteer: {
          url: "http://localhost",
          waitForTimeout: 2000,
          waitForAction: 500
    }
  }
}

```

**Comment by DavertMik** [comment]
`sec` should be optional. I think we have error in our typings. 
@elukoyanov can we fix this?
