### ISSUE TITLE
Junk character is seen at codeceptjs-cli-reporter

### ISSUE THREAD

**Issue by tusarnayak108** [codecept-js/CodeceptJS#2370]
#### What are you trying to achieve?
I want to write the log in a log file, used below option:
 #### What do you get instead?

I see the output in the test.log with few junk characters as below

[1mI want to be able to interact with ---- feature[22m --
  [35m[1mVerify service details in -----[22m[39m
  [32m[1m√ OK[22m[39m [90min 9573ms[39m

  [35m[1mVerify service details in ------ with genre filter[22m[39m
  [32m[1m√ OK[22m[39m [90min 8571ms[39m

[42m[1m  OK [22m[49m[42m[90m |[39m[49m[42m 2 passed  [49m[90m // 36s[39m

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: v2.6.2
* NodeJS Version: 12.16.1
* Operating System: Win 10
* puppeteer
* Configuration file:

```js
 mocha: {
    reporterOptions: {
      "codeceptjs-cli-reporter": {
        stdout: "./testresult/test.log",
        options: {
          verbose: false,
          steps: true,          
        },}}}

```

**Comment by DavertMik** [comment]
These are ASCII characters, they are used when you want to add colors to your output
try running the same with `--no-colors`

**Comment by tusarnayak108** [comment]
Thank you, it solved my issue
