### ISSUE TITLE
How I can execute parallel methods in codeceptjs?

### ISSUE THREAD

**Issue by aelzhanova** [codecept-js/CodeceptJS#2439]
#### What are you trying to achieve?
I need to wait for request after some actions. But I can't catch this because it's too fast. I think it will be great if I can execute parallel my filtration actions (fill Field and click filter button or something other I. actions) and I.waitForRequest, so my problem will be solved in this case 

#### What do you get instead?
request is too fast and I can't catch this - Timeout exceeded while waiting for event

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Timeout exceeded while waiting for event
```

> Provide test source code if related

```js
// paste test
```

### Details

- CodeceptJS version: 2.5.0
- NodeJS Version: v13.8.0
- Operating System: MacOs Mojave
- puppeteer

* Configuration file:

```js
# paste config here
```

**Comment by Vorobeyko** [comment]
I see that you are Russian, and I can suggest you to read my article for this: https://medium.com/@captain_sparrow/как-тестировать-ушедшие-запросы-с-помощью-puppeteer-playwright-1fbfc39e0ac3

**Comment by Vorobeyko** [comment]
And you can create helper with this functionality )

**Comment by aelzhanova** [comment]
yep, thanks! I saw this article, very interesting. I ended up solving the problem using page.on('request', request.. and wrote my helper, but a little bit another than you(Including because I use puppeteer), by and large, I relied on the https://stackoverflow.com/questions/52969381/how-can-i-capture-all-network-requests-and-full-response-data-when-loading-a-pag

**Comment by Vorobeyko** [comment]
@aelzhanova Ok! Can I close this issue?

**Comment by aelzhanova** [comment]
yes, thank you!

**Comment by aelzhanova** [comment]
@Vorobeyko if it's interesting for you my solution in this arcticle:
https://medium.com/@alsu.gareeva/codeceptjs-puppeteer-how-to-catch-too-fast-requests-1809e8c49fcf
