### ISSUE TITLE
for eclipse

### ISSUE THREAD

**Issue by bgsherman** [codecept-js/CodeceptJS#2486]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by Vorobeyko** [comment]
@bgsherman what is this problem about?

**Comment by bgsherman** [comment]
Sorry -- I did not (intentionally) file an issue -- I was reading through _existing_ issues when I had a hardware problem; anything I submitted here was by accident.
